/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;


import java.awt.Color;
import javax.swing.JOptionPane;



/**
 *
 * @author USER
 */
public class ElegirMenuEcuaciones extends javax.swing.JFrame {

    /**
     * Creates new form ElegirMenuEcuaciones
     */
    generarGrafica explicacion1 = new generarGrafica(1);
    generarGrafica explicacion2 = new generarGrafica(2);
    generarGrafica explicacion3 = new generarGrafica(3);
    generarGrafica explicacion4 = new generarGrafica(4);
    generarGrafica explicacion5 = new generarGrafica(5);
    generarGrafica explicacion6 = new generarGrafica(6);
    
    

 
    
    private double resultadoSol, resultadoZom;
    private static final long serialVersionUID = 1L;
    private int num =0;
    public ElegirMenuEcuaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);


        btnEc1.setBackground(null);
        btnEc2.setBackground(null);
        btnEc3.setBackground(null);
        btnEc4.setBackground(null);
        btnEc5.setBackground(null);
        btnEc6.setBackground(null);
        
   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelGrafica = new javax.swing.JPanel();
        lblNomEc = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnEc1 = new javax.swing.JButton();
        btnEc2 = new javax.swing.JButton();
        btnEc3 = new javax.swing.JButton();
        btnEc4 = new javax.swing.JButton();
        btnEc5 = new javax.swing.JButton();
        btnEc6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanelGrafica.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNomEc.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanelGraficaLayout = new javax.swing.GroupLayout(jPanelGrafica);
        jPanelGrafica.setLayout(jPanelGraficaLayout);
        jPanelGraficaLayout.setHorizontalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGraficaLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(lblNomEc)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanelGraficaLayout.setVerticalGroup(
            jPanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGraficaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomEc)
                .addGap(25, 25, 25))
        );

        btnRegresar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnRegresar.setText("Return");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(51, 51, 0), new java.awt.Color(255, 255, 51), new java.awt.Color(204, 204, 0)));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnStart.setText("Start");
        btnStart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 204, 0), new java.awt.Color(0, 153, 0)));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnEc1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEc1.setText("f(x)= x^(3) - 2x -5");
        btnEc1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 204), new java.awt.Color(0, 153, 153)));
        btnEc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEc1MouseExited(evt);
            }
        });
        btnEc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEc1ActionPerformed(evt);
            }
        });

        btnEc2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEc2.setText("f(x) = e ^(x) - 3x^(2)");
        btnEc2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 153), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 102, 255), new java.awt.Color(0, 102, 204)));
        btnEc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEc2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEc2MouseExited(evt);
            }
        });
        btnEc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEc2ActionPerformed(evt);
            }
        });

        btnEc3.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEc3.setText("f(x) = sin (x) - x^(2) + 2x +1");
        btnEc3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 51), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 51, 255)));
        btnEc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEc3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEc3MouseExited(evt);
            }
        });
        btnEc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEc3ActionPerformed(evt);
            }
        });

        btnEc4.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEc4.setText("f(x) = log(x) - 2x +3");
        btnEc4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 51), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204)));
        btnEc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEc4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEc4MouseExited(evt);
            }
        });
        btnEc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEc4ActionPerformed(evt);
            }
        });

        btnEc5.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEc5.setText("f(x) = sqr(x) - 2");
        btnEc5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 153), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 204), new java.awt.Color(51, 0, 204)));
        btnEc5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEc5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEc5MouseExited(evt);
            }
        });
        btnEc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEc5ActionPerformed(evt);
            }
        });

        btnEc6.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEc6.setText("f(x) = x^(2) - 4");
        btnEc6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 153), new java.awt.Color(51, 0, 51), new java.awt.Color(102, 51, 255), new java.awt.Color(102, 0, 204)));
        btnEc6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEc6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEc6MouseExited(evt);
            }
        });
        btnEc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEc6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("Choose the circuit for the race...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEc6, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEc4, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEc3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEc2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEc1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEc5, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEc1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnEc2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnEc3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnEc4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnEc5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnEc6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEc1ActionPerformed
        // TODO add your handling code here:
        this.num=0;
        btnEc2.setBackground(null);
        btnEc3.setBackground(null);
        btnEc4.setBackground(null);
        btnEc5.setBackground(null);
        btnEc6.setBackground(null);
        this.num = 1;
        btnEc1.setBackground(new Color(102, 204, 255));
        explicacion1.setVisible(true);
        
    }//GEN-LAST:event_btnEc1ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here
        if(num!=0){
        ingresarIntervalo elegirEc = new ingresarIntervalo(num);
        elegirEc.setVisible(true);
        elegirEc.labelEc();
        this.dispose();
        explicacion1.dispose();
        explicacion2.dispose();
        explicacion3.dispose();
        explicacion4.dispose();
        explicacion5.dispose();
        explicacion6.dispose();
        }else{
             JOptionPane.showMessageDialog(this, "NO EQUATION WAS CHOSEN\n"
                    + "Choose one");
        }
        
        InfoIntervalo intervalo = new InfoIntervalo();
        intervalo.setVisible(true);
        InfoIntervalo info = new InfoIntervalo();
        info.setVisible(true);
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnEc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEc2ActionPerformed
        // TODO add your handling code here:
        this.num=0;
        btnEc1.setBackground(null);
        btnEc3.setBackground(null);
        btnEc4.setBackground(null);
        btnEc5.setBackground(null);
        btnEc6.setBackground(null);
        this.num = 2;
        btnEc2.setBackground(new Color(102, 204, 255));
        explicacion2.setVisible(true);
    }//GEN-LAST:event_btnEc2ActionPerformed

    private void btnEc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEc3ActionPerformed
        // TODO add your handling code here:
        this.num=0;
        btnEc1.setBackground(null);
        btnEc2.setBackground(null);
        btnEc4.setBackground(null);
        btnEc5.setBackground(null);
        btnEc6.setBackground(null);
        this.num = 3;
        btnEc3.setBackground(new Color(102, 204, 255));
        explicacion3.setVisible(true);
    }//GEN-LAST:event_btnEc3ActionPerformed

    private void btnEc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEc4ActionPerformed
        // TODO add your handling code here:
        this.num=0;
        btnEc1.setBackground(Color.DARK_GRAY);
        btnEc2.setBackground(Color.DARK_GRAY);
        btnEc3.setBackground(Color.DARK_GRAY);
        btnEc5.setBackground(Color.DARK_GRAY);
        btnEc6.setBackground(Color.DARK_GRAY);
        this.num = 4;
        btnEc4.setBackground(new Color(102, 204, 255));
        explicacion4.setVisible(true);
    }//GEN-LAST:event_btnEc4ActionPerformed

    private void btnEc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEc5ActionPerformed
        // TODO add your handling code here
        this.num=0;
        btnEc1.setBackground(null);
        btnEc2.setBackground(null);
        btnEc3.setBackground(null);
        btnEc4.setBackground(null);
        btnEc6.setBackground(null);
        this.num = 5;
        btnEc5.setBackground(new Color(102, 204, 255));
        explicacion5.setVisible(true);
    }//GEN-LAST:event_btnEc5ActionPerformed

    private void btnEc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEc6ActionPerformed
        // TODO add your handling code here:
        this.num=0;
        btnEc1.setBackground(null);
        btnEc2.setBackground(null);
        btnEc3.setBackground(null);
        btnEc4.setBackground(null);
        btnEc5.setBackground(null);
        this.num = 6;
        btnEc6.setBackground(new Color(102, 204, 255));
        explicacion6.setVisible(true);
    }//GEN-LAST:event_btnEc6ActionPerformed

    private void btnEc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc1MouseExited
        // TODO add your handling code here
       if(num==0) {
           btnEc1.setBackground(null);
           lblNomEc.setText(null);
           explicacion1.dispose();
       
       }
    }//GEN-LAST:event_btnEc1MouseExited

    private void btnEc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc1MouseEntered
        // TODO add your handling code here:
        
        //Ecuación cúbica
        if(num==0){    
        
        explicacion1.setVisible(true);
        explicacion2.dispose();
        explicacion3.dispose();
        explicacion4.dispose();
        explicacion5.dispose();
        explicacion6.dispose();
        btnEc1.setBackground(new Color(102, 204, 255));//Color celeste código RGB
        lblNomEc.setText("Cubic Equation");
        }
     
        
    }//GEN-LAST:event_btnEc1MouseEntered

    private void btnEc2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc2MouseEntered
        // TODO add your handling code here:
        //Ecuación Exponencial
        if(num==0){
        explicacion1.dispose();
        explicacion2.setVisible(true);
        explicacion3.dispose();
        explicacion4.dispose();
        explicacion5.dispose();
        explicacion6.dispose();
        btnEc2.setBackground(new Color(102, 204, 255));//Color celeste código RGB
        lblNomEc.setText("Exponential Equation");
        }
     
    }//GEN-LAST:event_btnEc2MouseEntered

    private void btnEc2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc2MouseExited
        // TODO add your handling code here:
        if(num==0){
            btnEc2.setBackground(null);
            lblNomEc.setText(null);
            explicacion2.dispose();
        }
    }//GEN-LAST:event_btnEc2MouseExited

    private void btnEc3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc3MouseEntered
        // TODO add your handling code here:
        //Ecuacion Trigonométrica
        if(num==0){
        explicacion1.dispose();
        explicacion2.dispose();
        explicacion3.setVisible(true);
        explicacion4.dispose();
        explicacion5.dispose();
        explicacion6.dispose();
        btnEc3.setBackground(new Color(102, 204, 255));//Color celeste código RGB
        lblNomEc.setText("Trigonometric equation");
        }
    }//GEN-LAST:event_btnEc3MouseEntered

    private void btnEc3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc3MouseExited
        // TODO add your handling code here:
        if(num==0){
            btnEc3.setBackground(null);
            lblNomEc.setText(null);
            explicacion3.dispose();
        }
    }//GEN-LAST:event_btnEc3MouseExited

    private void btnEc4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc4MouseEntered
        // TODO add your handling code here:
        //Ecuación Logarítmica
        if(num==0){
        explicacion1.dispose();
        explicacion2.dispose();
        explicacion3.dispose();
        explicacion4.setVisible(true);
        explicacion5.dispose();
        explicacion6.dispose();
        btnEc4.setBackground(new Color(102, 204, 255));//Color celeste código RGB
        lblNomEc.setText("Logarithmic Equation");
        }
    }//GEN-LAST:event_btnEc4MouseEntered

    private void btnEc4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc4MouseExited
        // TODO add your handling code here:
        if(num==0){
            btnEc4.setBackground(null);
            lblNomEc.setText(null);
            explicacion4.dispose();
        }
    }//GEN-LAST:event_btnEc4MouseExited

    private void btnEc5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc5MouseEntered
        // TODO add your handling code here:
        //Ecuacion con radical
        if(num==0){
        explicacion1.dispose();
        explicacion2.dispose();
        explicacion3.dispose();
        explicacion4.dispose();
        explicacion5.setVisible(true);
        explicacion6.dispose();
        btnEc5.setBackground(new Color(102, 204, 255));//Color celeste código RGB
        lblNomEc.setText("Radical Equation");
        }
    }//GEN-LAST:event_btnEc5MouseEntered

    private void btnEc5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc5MouseExited
        // TODO add your handling code here:
        if(num==0){
            btnEc5.setBackground(null);
            lblNomEc.setText(null);
            explicacion5.dispose();
        }
    }//GEN-LAST:event_btnEc5MouseExited

    private void btnEc6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc6MouseEntered
        // TODO add your handling code here:
        //Ecuación cuadrática
        if(num==0){
        explicacion1.dispose();
        explicacion2.dispose();
        explicacion3.dispose();
        explicacion4.dispose();
        explicacion5.dispose();
        explicacion6.setVisible(true);
        btnEc6.setBackground(new Color(102, 204, 255));//Color celeste código RGB
        lblNomEc.setText("Quadratic Equation");
        }
    }//GEN-LAST:event_btnEc6MouseEntered

    private void btnEc6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEc6MouseExited
        // TODO add your handling code here:
        if(num==0){
            btnEc6.setBackground(null);
            lblNomEc.setText(null);
            explicacion6.dispose();
        }
    }//GEN-LAST:event_btnEc6MouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        explicacion1.dispose();
        explicacion2.dispose();
        explicacion3.dispose();
        explicacion4.dispose();
        explicacion5.dispose();
        explicacion6.dispose();
        preEleccion menu = new preEleccion();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        // TODO add your handling code here:
         btnStart.setBackground(new Color(0, 255, 0));//Color verde
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        // TODO add your handling code here:
         btnStart.setBackground(null);
    }//GEN-LAST:event_btnStartMouseExited

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setBackground(null);
    }//GEN-LAST:event_btnRegresarMouseExited

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEc1;
    private javax.swing.JButton btnEc2;
    private javax.swing.JButton btnEc3;
    private javax.swing.JButton btnEc4;
    private javax.swing.JButton btnEc5;
    private javax.swing.JButton btnEc6;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGrafica;
    private javax.swing.JLabel lblNomEc;
    // End of variables declaration//GEN-END:variables




}


