/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.applet.AudioClip;
import java.awt.Color;
import static java.awt.SystemColor.infoText;

/**
 *
 * @author USER
 */
public class infoMetodoSecante extends javax.swing.JFrame {

    /**
     * Creates new form infoMetodoSecante
     */
    public infoMetodoSecante() {
        initComponents();
         this.setLocationRelativeTo(null);
        
        //Maximizar la pantalla
        this.setExtendedState(MAXIMIZED_BOTH);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarJuego = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btnIniciarJuego.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnIniciarJuego.setText("Continue");
        btnIniciarJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 102), new java.awt.Color(0, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 255, 0)));
        btnIniciarJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseExited(evt);
            }
        });
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });

        btnRegresar1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnRegresar1.setText("Return");
        btnRegresar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 153), new java.awt.Color(153, 153, 0)));
        btnRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseExited(evt);
            }
        });
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        infoText.setEditable(false);
        infoText.setBackground(new java.awt.Color(0, 0, 0));
        infoText.setColumns(20);
        infoText.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        infoText.setForeground(new java.awt.Color(0, 255, 0));
        infoText.setLineWrap(true);
        infoText.setRows(5);
        infoText.setText("The secant method is like the compass for brave mathematicians venturing \nin search of the roots of a mysterious function!\n\nImagine you're exploring a map full of mountains and valleys,\ntrying to find the hidden treasure: the roots of that function are like treasures, \nthe points where the function touches the ground. \nThe secant method guides you through this unknown terrain using two nearby points \nin the function, like beacons in the darkness,\nto draw a secant line and estimate where the treasure lies.\n\nBut here's the thrilling part: the secant method doesn't stop there.\nIt thrives on iteration, urging mathematicians to refine their approximations. \nAfter drawing the initial secant line and estimating the location of the root,\nmathematicians calculate a new point where the secant line intersects the x-axis. \nThis new point becomes one of the endpoints for the next secant line. \nWith each iteration, the secant lines get closer and closer to \nthe true location of the root, unveiling the mathematical treasure \nthrough persistence and precision.\n\nThe secant method is your best friend when delving into the world \nof equations and function roots. It helps you find mathematical treasures quickly and accurately, turning you into a true adventurer of numbers.");
        infoText.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        infoText.setCaretColor(new java.awt.Color(102, 102, 102));
        infoText.setSelectedTextColor(new java.awt.Color(0, 255, 51));
        infoText.setSelectionColor(new java.awt.Color(51, 255, 0));
        jScrollPane1.setViewportView(infoText);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 48)); // NOI18N
        jLabel1.setText("Secant Method");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(507, 507, 507))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseEntered
        // TODO add your handling code here:
        btnIniciarJuego.setBackground(new Color(0, 255, 0));//Color verde
    }//GEN-LAST:event_btnIniciarJuegoMouseEntered

    private void btnIniciarJuegoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseExited
        // TODO add your handling code here:
        btnIniciarJuego.setBackground(null);//Volver a color default
    }//GEN-LAST:event_btnIniciarJuegoMouseExited

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        // TODO add your handling code here:
        preEleccion pre = new preEleccion();
        pre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    private void btnRegresar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseEntered
        // TODO add your handling code here:
        btnRegresar1.setBackground(new Color(255,255,0));//Color amarillo código RGB
    }//GEN-LAST:event_btnRegresar1MouseEntered

    private void btnRegresar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseExited
        // TODO add your handling code here:
        btnRegresar1.setBackground(null);//Volver a color default
    }//GEN-LAST:event_btnRegresar1MouseExited

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        infoInicial info = new infoInicial();
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JTextArea infoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
