/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class infoError extends javax.swing.JFrame {

    /**
     * Creates new form infoError
     */
    public infoError() {
        initComponents();
        // Crear un borde personalizado
        Border border = BorderFactory.createLineBorder(Color.BLACK, 5);

        // Establecer el borde en el JFrame
        this.getRootPane().setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarJuego = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(450, 250));
        setUndecorated(true);
        setResizable(false);

        btnIniciarJuego.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnIniciarJuego.setText("Next");
        btnIniciarJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 102), new java.awt.Color(0, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 255, 0)));
        btnIniciarJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseExited(evt);
            }
        });
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });

        infoText.setEditable(false);
        infoText.setBackground(new java.awt.Color(0, 0, 0));
        infoText.setColumns(20);
        infoText.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        infoText.setForeground(new java.awt.Color(0, 255, 0));
        infoText.setLineWrap(true);
        infoText.setRows(5);
        infoText.setText("Oh, and don't forget about error. \nIt's like the margin of error\nin a game of darts:\nthe smaller it is, the closer you are\nto hitting the bull's-eye. \nBut reducing the error too much\ncan lead you to throw more darts,\nor in our case, \nmore mathematical iterations.\nSo balancing accuracy \nwith efficiency is key.");
        infoText.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        infoText.setCaretColor(new java.awt.Color(102, 102, 102));
        infoText.setSelectedTextColor(new java.awt.Color(0, 255, 51));
        infoText.setSelectionColor(new java.awt.Color(51, 255, 0));
        jScrollPane1.setViewportView(infoText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseEntered
        // TODO add your handling code here:
        btnIniciarJuego.setBackground(new Color(0, 255, 0));//Color verde
    }//GEN-LAST:event_btnIniciarJuegoMouseEntered

    private void btnIniciarJuegoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseExited
        // TODO add your handling code here:
        btnIniciarJuego.setBackground(null);//Volver a color default
    }//GEN-LAST:event_btnIniciarJuegoMouseExited

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JTextArea infoText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
