/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.applet.AudioClip;
import java.awt.Color;

/**
 *
 * @author USER
 */
public class infoInicial extends javax.swing.JFrame {

    /**
     * Creates new form infoInicial
     */
    
    AudioClip sonidoFondo=java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/darkdrone-18159.wav"));;
  
    public infoInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Maximizar la pantalla
        this.setExtendedState(MAXIMIZED_BOTH);
        infoText.setEditable(false);
        
        
        sonidoFondo.play();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIniciarJuego = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        btnIniciarJuego.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnIniciarJuego.setText("Accept");
        btnIniciarJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 102), new java.awt.Color(0, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 255, 0)));
        btnIniciarJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseExited(evt);
            }
        });
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });

        btnRegresar1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnRegresar1.setText("Return");
        btnRegresar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 153), new java.awt.Color(153, 153, 0)));
        btnRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseExited(evt);
            }
        });
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        infoText.setBackground(new java.awt.Color(0, 0, 0));
        infoText.setColumns(20);
        infoText.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        infoText.setForeground(new java.awt.Color(0, 255, 0));
        infoText.setLineWrap(true);
        infoText.setRows(5);
        infoText.setText("In a world ravaged by apocalypse, where humanity faces a constant threat from\nhordes of bloodthirsty undead, emerges a legend that has captured \nthe imagination of those still struggling to survive: the legendary Sacred Diamond.\n\nIt is said that this diamond, whose existence is lost in the mists of time,\npossesses unparalleled power: the ability to transform all living beings \non earth into followers of either side, be it the relentless soldiers \nfighting for humanity's survival, or the ruthless zombies seeking to consume \neverything in their path.\n\nThe key to unraveling the whereabouts of this mysterious diamond lies in an \nancient mathematical secret, guarded jealously by generations.\nIt is said that only those capable of comprehending and applying the \nnumerical method of the secant will be able to decipher \nthe riddles that lead to the Sacred Diamond.\n\nNow, two brave and cunning players face a transcendent choice: \nto join the ranks of the soldiers or succumb to the darkness of the zombies? \nThe battle for the Sacred Diamond is about to begin. \nAre you prepared to choose your side and unravel the \nmathematical secrets that will determine the fate of humanity?\nThe future of this world lies in your hands.");
        infoText.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        infoText.setCaretColor(new java.awt.Color(102, 102, 102));
        infoText.setSelectedTextColor(new java.awt.Color(0, 255, 51));
        infoText.setSelectionColor(new java.awt.Color(51, 255, 0));
        jScrollPane1.setViewportView(infoText);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/SoldadoIcono.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/pixil-frame-0 (15).png"))); // NOI18N
        jLabel1.setText("Game Info");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/pixil-frame-0 (3).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(498, 498, 498))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        // TODO add your handling code here:
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/cute-level-up-3-189853.wav"));
        sonido.play();
        infoMetodoSecante metodo = new infoMetodoSecante();
        metodo.setVisible(true);
        this.dispose();
        sonidoFondo.stop();
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/game-over-arcade-6435.wav"));
        sonido.play();
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
        sonidoFondo.stop();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnIniciarJuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseEntered
        // TODO add your handling code here:
        btnIniciarJuego.setBackground(new Color(0, 255, 0));//Color verde 
    }//GEN-LAST:event_btnIniciarJuegoMouseEntered

    private void btnIniciarJuegoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseExited
        // TODO add your handling code here:
        btnIniciarJuego.setBackground(null);//Volver a color default 
    }//GEN-LAST:event_btnIniciarJuegoMouseExited

    private void btnRegresar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseEntered
        // TODO add your handling code here:
        btnRegresar1.setBackground(new Color(255,255,0));//Color amarillo código RGB
    }//GEN-LAST:event_btnRegresar1MouseEntered

    private void btnRegresar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseExited
        // TODO add your handling code here:
        btnRegresar1.setBackground(null);//Volver a color default 
    }//GEN-LAST:event_btnRegresar1MouseExited

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JTextArea infoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
