/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.applet.AudioClip;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.WindowConstants;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class infoFinal extends javax.swing.JFrame {

    /**
     * Creates new form infoFinal
     */
    public infoFinal() {
        initComponents();
        // Crear un borde personalizado
        Border border = BorderFactory.createLineBorder(Color.BLACK, 5);

        // Establecer el borde en el JFrame
        this.getRootPane().setBorder(border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNuevaPartida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoText = new javax.swing.JTextArea();
        btnFin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 250));
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/Diamond.png"))); // NOI18N

        btnNuevaPartida.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnNuevaPartida.setText("Play Again");
        btnNuevaPartida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 102), new java.awt.Color(0, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 255, 0)));
        btnNuevaPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaPartidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaPartidaMouseExited(evt);
            }
        });
        btnNuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPartidaActionPerformed(evt);
            }
        });

        infoText.setEditable(false);
        infoText.setBackground(new java.awt.Color(0, 0, 0));
        infoText.setColumns(20);
        infoText.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        infoText.setForeground(new java.awt.Color(0, 255, 0));
        infoText.setLineWrap(true);
        infoText.setRows(5);
        infoText.setText("You have proven to be a formidable leader\nand a true hero\nin this apocalyptic world.\n\nThe Sacred Diamond now rests\nin the hands of your team,\nand your name will be etched\nin history\nas the conqueror who found it.");
        infoText.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        infoText.setCaretColor(new java.awt.Color(102, 102, 102));
        infoText.setSelectedTextColor(new java.awt.Color(0, 255, 51));
        infoText.setSelectionColor(new java.awt.Color(51, 255, 0));
        jScrollPane1.setViewportView(infoText);

        btnFin.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnFin.setText("Game Over");
        btnFin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 0, 0)));
        btnFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinMouseExited(evt);
            }
        });
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnFin, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaPartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaPartidaMouseEntered
        // TODO add your handling code here:
        btnNuevaPartida.setBackground(new Color(0, 255, 0));//Color verde
    }//GEN-LAST:event_btnNuevaPartidaMouseEntered

    private void btnNuevaPartidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaPartidaMouseExited
        // TODO add your handling code here:
        btnNuevaPartida.setBackground(null);//Volver a color default
    }//GEN-LAST:event_btnNuevaPartidaMouseExited

    private void btnNuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPartidaActionPerformed
        // TODO add your handling code here:
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/cute-level-up-3-189853.wav"));
        sonido.play();
        preEleccion menu = new preEleccion();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNuevaPartidaActionPerformed

    private void btnFinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinMouseEntered
        // TODO add your handling code here:
        btnFin.setBackground(new Color(255, 150, 150));//Color rojo código RGB
    }//GEN-LAST:event_btnFinMouseEntered

    private void btnFinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinMouseExited
        // TODO add your handling code here:
        btnFin.setBackground(null);
    }//GEN-LAST:event_btnFinMouseExited

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        // TODO add your handling code here:
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/game-over-arcade-6435.wav"));
        sonido.play();
        System.exit(0); 
       
       
    }//GEN-LAST:event_btnFinActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnNuevaPartida;
    private javax.swing.JTextArea infoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
