/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class infoGanador extends javax.swing.JFrame {

    /**
     * Creates new form infoGanador
     */
    String ganador;
    public infoGanador() {
        initComponents();
        // Crear un borde personalizado
        Border border = BorderFactory.createLineBorder(Color.BLACK, 5);

        // Establecer el borde en el JFrame
        this.getRootPane().setBorder(border);
    }

    public void setGanador(String ganador) {
        this.ganador = ganador;
    }
    
    
    public void premiacion (String nombre){
        ImageIcon iconoZombie = new ImageIcon(getClass().getResource("/Gráficos/pixil-frame-0 (3).png"));
        ImageIcon iconoSoldado = new ImageIcon(getClass().getResource("/Gráficos/soldadoIcono.png"));
        if(nombre == "soldado"){
            lblJugador.setIcon(iconoSoldado);
            lblCampeon.setText("Congratulations Soldier!");
            
        }else{
            lblJugador.setIcon(iconoZombie);
            lblCampeon.setText("Congratulations Zombie!");
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarJuego = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblCampeon = new javax.swing.JLabel();
        lblJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(450, 250));
        setUndecorated(true);

        btnIniciarJuego.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnIniciarJuego.setText("Next");
        btnIniciarJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 102), new java.awt.Color(0, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 255, 0)));
        btnIniciarJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseExited(evt);
            }
        });
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });

        infoText.setEditable(false);
        infoText.setBackground(new java.awt.Color(0, 0, 0));
        infoText.setColumns(20);
        infoText.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        infoText.setForeground(new java.awt.Color(0, 255, 0));
        infoText.setLineWrap(true);
        infoText.setRows(5);
        infoText.setText("Congratulations!\nYou have emerged triumphant inthis epic contest in search ofthe legendary Sacred Diamond. \nYour victory is a testament\nto your ingenuity, bravery and\nstrategic skill.\n");
        infoText.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 51, 51)));
        infoText.setCaretColor(new java.awt.Color(102, 102, 102));
        infoText.setSelectedTextColor(new java.awt.Color(0, 255, 51));
        infoText.setSelectionColor(new java.awt.Color(51, 255, 0));
        jScrollPane1.setViewportView(infoText);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/Diamond.png"))); // NOI18N

        lblCampeon.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        lblCampeon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCampeon.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampeon))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblJugador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCampeon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblJugador)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21)
                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseEntered
        // TODO add your handling code here:
        btnIniciarJuego.setBackground(new Color(0, 255, 0));//Color verde
    }//GEN-LAST:event_btnIniciarJuegoMouseEntered

    private void btnIniciarJuegoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseExited
        // TODO add your handling code here:
        btnIniciarJuego.setBackground(null);//Volver a color default
    }//GEN-LAST:event_btnIniciarJuegoMouseExited

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        // TODO add your handling code here:
        infoExplicacionFinal explicacion = new infoExplicacionFinal();
        explicacion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
   
       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JTextArea infoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCampeon;
    private javax.swing.JLabel lblJugador;
    // End of variables declaration//GEN-END:variables
}
