/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ingresarEcExponencial extends javax.swing.JFrame {

    /**
     * Creates new form ingresarEcExponencial
     */
    public ingresarEcExponencial() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Maximizar la pantalla
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtE3 = new javax.swing.JTextField();
        txtC1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtE1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtE2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtC2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        txtE4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtC3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtE5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtE6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnGraficar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtE3.setBackground(new java.awt.Color(0, 0, 0));
        txtE3.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtE3.setForeground(new java.awt.Color(0, 255, 0));
        txtE3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 0, 255))); // NOI18N
        txtE3.setCaretColor(new java.awt.Color(255, 255, 255));
        txtE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE3ActionPerformed(evt);
            }
        });

        txtC1.setBackground(new java.awt.Color(0, 0, 0));
        txtC1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC1.setForeground(new java.awt.Color(0, 255, 0));
        txtC1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC1ActionPerformed(evt);
            }
        });
        txtC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtC1KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel7.setText("^(");

        txtE1.setBackground(new java.awt.Color(0, 0, 0));
        txtE1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtE1.setForeground(new java.awt.Color(0, 255, 0));
        txtE1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(0, 255, 255))); // NOI18N
        txtE1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("Exponential Equation");

        jLabel12.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel12.setText("X+");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel2.setText("Enter the value of the constants you will use to build your function...");

        txtE2.setBackground(new java.awt.Color(0, 0, 0));
        txtE2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtE2.setForeground(new java.awt.Color(0, 255, 0));
        txtE2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(0, 255, 255))); // NOI18N
        txtE2.setCaretColor(new java.awt.Color(255, 255, 255));
        txtE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/exponencial.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel14.setText(") + ");

        txtC2.setBackground(new java.awt.Color(0, 0, 0));
        txtC2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC2.setForeground(new java.awt.Color(0, 255, 0));
        txtC2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC2.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC2ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel16.setText("^(");

        jLabel18.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel18.setText("X +");

        btnRegresar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnRegresar.setText("Return");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnStart.setText("Continue");
        btnStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        txtE4.setBackground(new java.awt.Color(0, 0, 0));
        txtE4.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtE4.setForeground(new java.awt.Color(0, 255, 0));
        txtE4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 0, 255))); // NOI18N
        txtE4.setCaretColor(new java.awt.Color(255, 255, 255));
        txtE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE4ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel15.setText(") + ");

        txtC3.setBackground(new java.awt.Color(0, 0, 0));
        txtC3.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC3.setForeground(new java.awt.Color(0, 255, 0));
        txtC3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC3.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC3ActionPerformed(evt);
            }
        });
        txtC3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtC3KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel8.setText("^(");

        txtE5.setBackground(new java.awt.Color(0, 0, 0));
        txtE5.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtE5.setForeground(new java.awt.Color(0, 255, 0));
        txtE5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N
        txtE5.setCaretColor(new java.awt.Color(255, 255, 255));
        txtE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE5ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel13.setText("X+");

        txtE6.setBackground(new java.awt.Color(0, 0, 0));
        txtE6.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtE6.setForeground(new java.awt.Color(0, 255, 0));
        txtE6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E6", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 0))); // NOI18N
        txtE6.setCaretColor(new java.awt.Color(255, 255, 255));
        txtE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtE6ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel17.setText(") ");

        btnGraficar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnGraficar.setText("chart plot");
        btnGraficar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));
        btnGraficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGraficarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGraficarMouseExited(evt);
            }
        });
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel4.setText("Ecuación de la forma:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtC1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtC2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtE3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtE4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtC3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtE5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtE6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(486, 486, 486))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtE4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtE5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtE6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtC3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel8)
                    .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18)
                    .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtC1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtC2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtE3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE3ActionPerformed

    private void txtC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC1ActionPerformed

    private void txtC1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtC1KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtC1KeyTyped

    private void txtE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE1ActionPerformed

    private void txtE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE2ActionPerformed

    private void txtC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC2ActionPerformed

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setBackground(new Color(255, 255, 0));//Color amarillo código RGB
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setBackground(null);//Color default
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        ingresarEcMenu menu = new ingresarEcMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        // TODO add your handling code here:
        btnStart.setBackground(new Color(0, 255, 0));//Color verde
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        // TODO add your handling code here:
        btnStart.setBackground(null);//Color default
    }//GEN-LAST:event_btnStartMouseExited

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        if (Double.parseDouble(txtC1.getText()) == 0 && Double.parseDouble(txtC2.getText()) == 0 && Double.parseDouble(txtC3.getText()) == 0) {
            JOptionPane.showMessageDialog(this, "El valor de todas las constantes son nulas\n"
                    + "Ingresa al menos un valor diferente a cero");


        
        }else{
            ingresarIntervalo intervalo = new ingresarIntervalo(8);
            intervalo.setC1(Double.parseDouble(txtC1.getText()));
            intervalo.setC2(Double.parseDouble(txtC2.getText()));
            intervalo.setC3(Double.parseDouble(txtC3.getText()));
            intervalo.setE1(Double.parseDouble(txtE1.getText()));
            intervalo.setE2(Double.parseDouble(txtE2.getText()));
            intervalo.setE3(Double.parseDouble(txtE3.getText()));
            intervalo.setE4(Double.parseDouble(txtE4.getText()));
            intervalo.setE5(Double.parseDouble(txtE5.getText()));
            intervalo.setE6(Double.parseDouble(txtE6.getText()));
            intervalo.setVisible(true);
            intervalo.labelEc();
            InfoIntervalo info = new InfoIntervalo();
            info.setVisible(true);
            
            this.dispose();
            
            
        }   

    }//GEN-LAST:event_btnStartActionPerformed

    private void txtE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE4ActionPerformed

    private void txtC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC3ActionPerformed

    private void txtC3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtC3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC3KeyTyped

    private void txtE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE5ActionPerformed

    private void txtE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtE6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtE6ActionPerformed

    private void btnGraficarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficarMouseEntered
        // TODO add your handling code here:
        btnGraficar.setBackground(new Color(102, 204, 255));//Color celeste código RGB
    }//GEN-LAST:event_btnGraficarMouseEntered

    private void btnGraficarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficarMouseExited
        // TODO add your handling code here:
        btnGraficar.setBackground(null);//Color default

    }//GEN-LAST:event_btnGraficarMouseExited

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        generarGrafica grafica = new generarGrafica(8,Double.valueOf(txtC1.getText()), Double.valueOf(txtC2.getText()),Double.valueOf(txtC3.getText()),Double.valueOf(txtE1.getText()), 
                Double.valueOf(txtE2.getText()),Double.valueOf(txtE3.getText()),Double.valueOf(txtE4.getText()),Double.valueOf(txtE5.getText()),Double.valueOf(txtE6.getText()));
        grafica.setVisible(true);

    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtC1;
    private javax.swing.JTextField txtC2;
    private javax.swing.JTextField txtC3;
    private javax.swing.JTextField txtE1;
    private javax.swing.JTextField txtE2;
    private javax.swing.JTextField txtE3;
    private javax.swing.JTextField txtE4;
    private javax.swing.JTextField txtE5;
    private javax.swing.JTextField txtE6;
    // End of variables declaration//GEN-END:variables
}
