/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ingresarEcLineal extends javax.swing.JFrame {

    /**
     * Creates new form ingresoEcLineal
     * 
     * 
     */
    
    
    public ingresarEcLineal() {
        initComponents();
         this.setLocationRelativeTo(null);
        
        //Maximizar la pantalla
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtC1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtC2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtC3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtC4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtC6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtC5 = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGraficar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtC1.setBackground(new java.awt.Color(0, 0, 0));
        txtC1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC1.setForeground(new java.awt.Color(0, 255, 0));
        txtC1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC1ActionPerformed(evt);
            }
        });
        txtC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtC1KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel7.setText("X^(5) +");

        txtC2.setBackground(new java.awt.Color(0, 0, 0));
        txtC2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC2.setForeground(new java.awt.Color(0, 255, 0));
        txtC2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC2.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel12.setText("X^(4) +");

        txtC3.setBackground(new java.awt.Color(0, 0, 0));
        txtC3.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC3.setForeground(new java.awt.Color(0, 255, 0));
        txtC3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC3.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel14.setText("X^(3) +");

        txtC4.setBackground(new java.awt.Color(0, 0, 0));
        txtC4.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC4.setForeground(new java.awt.Color(0, 255, 0));
        txtC4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC4.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel16.setText("X^(2) +");

        txtC6.setBackground(new java.awt.Color(0, 0, 0));
        txtC6.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC6.setForeground(new java.awt.Color(0, 255, 0));
        txtC6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C6", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC6.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC6ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel18.setText("X +");

        txtC5.setBackground(new java.awt.Color(0, 0, 0));
        txtC5.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtC5.setForeground(new java.awt.Color(0, 255, 0));
        txtC5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtC5.setCaretColor(new java.awt.Color(255, 255, 255));
        txtC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtC5ActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnStart.setText("Continue");
        btnStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartMouseExited(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnRegresar.setText("Return");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("Linear Equation");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel2.setText("Enter the value of the constants you will use to build your function...");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/lineal.png"))); // NOI18N

        btnGraficar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnGraficar.setText("chart plot");
        btnGraficar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));
        btnGraficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGraficarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGraficarMouseExited(evt);
            }
        });
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel4.setText("Equation form:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(txtC1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtC2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtC3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtC4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtC5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtC6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(jLabel1)))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtC2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel18)
                            .addComponent(txtC3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtC1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtC4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtC5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16)
                            .addComponent(txtC6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC1ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtC1ActionPerformed

    private void txtC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC2ActionPerformed

    private void txtC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC3ActionPerformed

    private void txtC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC4ActionPerformed

    private void txtC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC6ActionPerformed

    private void txtC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtC5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtC5ActionPerformed

    private void txtC1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtC1KeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtC1KeyTyped

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        if (Double.parseDouble(txtC1.getText()) == 0 && Double.parseDouble(txtC2.getText()) == 0 && Double.parseDouble(txtC3.getText()) == 0 && Double.parseDouble(txtC4.getText()) == 0 && Double.parseDouble(txtC5.getText()) == 0 && Double.parseDouble(txtC6.getText()) == 0) {
            JOptionPane.showMessageDialog(this, "El valor de todas las constantes son nulas\n"
                    + "Ingresa al menos un valor diferente a cero");


        
        }else{
            ingresarIntervalo intervalo = new ingresarIntervalo(7);
            intervalo.setC1(Double.parseDouble(txtC1.getText()));
            intervalo.setC2(Double.parseDouble(txtC2.getText()));
            intervalo.setC3(Double.parseDouble(txtC3.getText()));
            intervalo.setC4(Double.parseDouble(txtC4.getText()));
            intervalo.setC5(Double.parseDouble(txtC5.getText()));
            intervalo.setC6(Double.parseDouble(txtC6.getText()));
            intervalo.setVisible(true);
            intervalo.labelEc();
            InfoIntervalo info = new InfoIntervalo();
            info.setVisible(true);
            this.dispose();
            
        }   
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        ingresarEcMenu menu = new ingresarEcMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseEntered
        // TODO add your handling code here:
         btnStart.setBackground(new Color(0, 255, 0));//Color verde 
    }//GEN-LAST:event_btnStartMouseEntered

    private void btnStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseExited
        // TODO add your handling code here:
         btnStart.setBackground(null);//Color default
    }//GEN-LAST:event_btnStartMouseExited

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setBackground(new Color(255, 255, 0));//Color amarillo código RGB
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setBackground(null);//Color default
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnGraficarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficarMouseEntered
        // TODO add your handling code here:
        btnGraficar.setBackground(new Color(102, 204, 255));//Color celeste código RGB
    }//GEN-LAST:event_btnGraficarMouseEntered

    private void btnGraficarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficarMouseExited
        // TODO add your handling code here:
         btnGraficar.setBackground(null);//Color default
         
    }//GEN-LAST:event_btnGraficarMouseExited

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        generarGrafica grafica = new generarGrafica(7,Double.valueOf(txtC1.getText()), Double.valueOf(txtC2.getText()),Double.valueOf(txtC3.getText()),Double.valueOf(txtC4.getText()), Double.valueOf(txtC5.getText()),Double.valueOf(txtC6.getText()));
        grafica.setVisible(true);
        
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtC1;
    private javax.swing.JTextField txtC2;
    private javax.swing.JTextField txtC3;
    private javax.swing.JTextField txtC4;
    private javax.swing.JTextField txtC5;
    private javax.swing.JTextField txtC6;
    // End of variables declaration//GEN-END:variables
}
