/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class ingresarEcMenuTrigo extends javax.swing.JFrame {
    
    private String ecuacion;

    /**
     * Creates new form ingresarEcMenu
     */
    public ingresarEcMenuTrigo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Maximizar la pantalla
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEcCos = new javax.swing.JButton();
        btnEcTan = new javax.swing.JButton();
        btnEcSeno = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEcCos.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEcCos.setText("Cosine");
        btnEcCos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnEcCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEcCosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEcCosMouseExited(evt);
            }
        });
        btnEcCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcCosActionPerformed(evt);
            }
        });

        btnEcTan.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEcTan.setText("Tangent");
        btnEcTan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnEcTan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEcTanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEcTanMouseExited(evt);
            }
        });
        btnEcTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcTanActionPerformed(evt);
            }
        });

        btnEcSeno.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEcSeno.setText("Sine");
        btnEcSeno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnEcSeno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEcSenoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEcSenoMouseExited(evt);
            }
        });
        btnEcSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcSenoActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnRegresar.setText("Return");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("Choose wisely....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnEcCos, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEcTan, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEcSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(467, 467, 467))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(772, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(521, 521, 521))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEcSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEcCos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEcTan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEcSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcSenoActionPerformed
        // TODO add your handling code here:
        ingresarEcTrigoSen ecSen = new ingresarEcTrigoSen();
        ecSen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcSenoActionPerformed

    private void btnEcTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcTanActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        ingresarEcTrigoTan ecTan = new ingresarEcTrigoTan();
        ecTan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcTanActionPerformed

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setBackground(new Color(255, 255, 153));//Color amarillo código RGB
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setBackground(null);//Color default
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnEcSenoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcSenoMouseEntered
        // TODO add your handling code here:
         btnEcSeno.setBackground(new Color(255, 153, 0));//Color anaranjado código RGB
    }//GEN-LAST:event_btnEcSenoMouseEntered

    private void btnEcSenoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcSenoMouseExited
        // TODO add your handling code here:
        btnEcSeno.setBackground(null);//Color default
    }//GEN-LAST:event_btnEcSenoMouseExited

    private void btnEcCosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcCosMouseEntered
        // TODO add your handling code here:
        btnEcCos.setBackground(new Color(255, 153, 0));//Color anaranjado código RGB
    }//GEN-LAST:event_btnEcCosMouseEntered

    private void btnEcCosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcCosMouseExited
        // TODO add your handling code here:
        btnEcCos.setBackground(null);//Color default
    }//GEN-LAST:event_btnEcCosMouseExited

    private void btnEcTanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcTanMouseEntered
        // TODO add your handling code here:
        btnEcTan.setBackground(new Color(255, 153, 0));//Color anaranjado código RGB
    }//GEN-LAST:event_btnEcTanMouseEntered

    private void btnEcTanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcTanMouseExited
        // TODO add your handling code here:
        btnEcTan.setBackground(null);//Color default
    }//GEN-LAST:event_btnEcTanMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        preEleccion menu = new preEleccion();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEcCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcCosActionPerformed
        // TODO add your handling code here:
        ingresarEcTrigoCos ecCos = new ingresarEcTrigoCos();
        ecCos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcCosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEcCos;
    private javax.swing.JButton btnEcSeno;
    private javax.swing.JButton btnEcTan;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
