/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author USER
 */
public class ingresarIntervalo extends javax.swing.JFrame {

    /**
     * Creates new form Elección
     */
    int ecuacion;
    double error,x0Sol,x1Sol,x0Zom,x1Zom,resSol,resZom,c1,c2,c3,c4,c5, c6, e1, e2, e3, e4, e5, e6;
    String ecuacionText, base;
    public ingresarIntervalo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        
        // Clean up open preview windows
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof generarGrafica || window instanceof imagenEcIngreso) {
                window.dispose();
            }
        }
    }
    
     public ingresarIntervalo(int ecuacion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ecuacion = ecuacion;
        
        // Clean up open preview windows
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof generarGrafica || window instanceof imagenEcIngreso) {
                window.dispose();
            }
        }
    }

    public void setC1(double c1) {
        this.c1 = c1;
        
    }

    public void setC2(double c2) {
        this.c2 = c2;
    }

    public void setC3(double c3) {
        this.c3 = c3;
    }

    public void setC4(double c4) {
        this.c4 = c4;
    }

    public void setC5(double c5) {
        this.c5 = c5;
    }

    public void setC6(double c6) {
        this.c6 = c6;
    }

    public void setE1(double e1) {
        this.e1 = e1;
    }

    public void setE2(double e2) {
        this.e2 = e2;
    }

    public void setE3(double e3) {
        this.e3 = e3;
    }

    public void setE4(double e4) {
        this.e4 = e4;
    }

    public void setE5(double e5) {
        this.e5 = e5;
    }

    public void setE6(double e6) {
        this.e6 = e6;
    }

    public void setBase(String base) {
        this.base = base;
    }
    
    
    
    
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtX0Sol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtX1Sol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEcSoldado2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblEcuacion = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblZombie = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtX0Zom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtX1Zom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbError = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnSalir.setText("RETURN");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));

        txtX0Sol.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtX0Sol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtX0SolMouseClicked(evt);
            }
        });
        txtX0Sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX0SolActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel2.setText("x1");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel4.setText("x0");

        txtX1Sol.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtX1Sol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtX1SolMouseClicked(evt);
            }
        });
        txtX1Sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX1SolActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel5.setText("Soldier enter your interval:");

        lblEcSoldado2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lblEcSoldado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcSoldado2.setText("SOLDIER");
        lblEcSoldado2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/SoldadoIcono.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel10.setText("This will determine your speed.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEcSoldado2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(49, 49, 49))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtX0Sol, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtX1Sol, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblEcSoldado2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX0Sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtX1Sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        lblEcuacion.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        lblEcuacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEcuacion.setText("Aquí Ecuación Elegida");
        lblEcuacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnIniciar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnIniciar.setText("START");
        btnIniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarMouseExited(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));

        lblZombie.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lblZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZombie.setText("ZOMBIE");
        lblZombie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel1.setText("x0");

        txtX0Zom.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtX0Zom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtX0ZomMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel3.setText("x1");

        txtX1Zom.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtX1Zom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtX1ZomMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/pixil-frame-0 (3).png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel6.setText("Zombie enter your interval:");

        jLabel12.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel12.setText("This will determine your speed.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtX0Zom, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtX1Zom, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX0Zom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtX1Zom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        lbl5.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl5.setText("Error");

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel7.setText("Enter the error:");

        cbError.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        cbError.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.01", "0.02", "0.05" }));
        cbError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbErrorMouseClicked(evt);
            }
        });

        jButton1.setText("i");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1)))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblEcuacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(958, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl5)
                            .addComponent(cbError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(80, 80, 80)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1015, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        //Caálculo de ElegirMenuEcuaciones
         this.x0Sol = Double.parseDouble(txtX0Sol.getText());
         this.x1Sol = Double.parseDouble(txtX1Sol.getText());
         this.x0Zom = Double.parseDouble(txtX0Zom.getText());
         this.x1Zom = Double.parseDouble(txtX1Zom.getText());
         this.error = Double.parseDouble(cbError.getSelectedItem().toString());
         SoldadoVsZombie jugador1 = null;
         SoldadoVsZombie jugador2 = null;
         
        if(ecuacion==7){
            jugador1 = new SoldadoVsZombie(ecuacion, x0Sol, x1Sol, error,c1,c2,c3,c4,c5,c6);
            jugador1.resolverEc();
            resSol = jugador1.getResult();

            jugador2 = new SoldadoVsZombie(ecuacion, x0Zom, x1Zom, error,c1,c2,c3,c4,c5,c6);
            jugador2.resolverEc();
            resZom = jugador2.getResult();
        }else if(ecuacion==8){
            jugador1 = new SoldadoVsZombie(ecuacion, x0Sol, x1Sol, error,c1,c2,c3,e1, e2, e3, e4, e5, e6);
            jugador1.resolverEc();
            resSol = jugador1.getResult();

            jugador2 = new SoldadoVsZombie(ecuacion, x0Zom, x1Zom, error,c1,c2,c3, e1, e2, e3, e4, e5, e6);
            jugador2.resolverEc();
            resZom = jugador2.getResult();
        }else if(ecuacion == 9 || ecuacion == 10 || ecuacion == 11){
            jugador1 = new SoldadoVsZombie(ecuacion, x0Sol, x1Sol, error,c1,c2,c3,c4);
            jugador1.resolverEc();
            resSol = jugador1.getResult();

            jugador2 = new SoldadoVsZombie(ecuacion, x0Zom, x1Zom, error,c1,c2,c3, c4);
            jugador2.resolverEc();
            resZom = jugador2.getResult();
        }else if(ecuacion == 12){
            jugador1 = new SoldadoVsZombie(ecuacion, x0Sol, x1Sol, error, base, c1,c2,c3,c4);
            jugador1.resolverEc();
            resSol = jugador1.getResult();

            jugador2 = new SoldadoVsZombie(ecuacion, x0Zom, x1Zom, error, base, c1,c2,c3, c4);
            jugador2.resolverEc();
            resZom = jugador2.getResult();
        }else{
            jugador1 = new SoldadoVsZombie(ecuacion, x0Sol, x1Sol, error);
            jugador1.resolverEc();
            resSol = jugador1.getResult();

            jugador2 = new SoldadoVsZombie(ecuacion, x0Zom, x1Zom, error);
            jugador2.resolverEc();
            resZom = jugador2.getResult();
        }
          
        // Verify convergence for both players. Show warning and halt if failure.
        if (jugador1 == null || jugador2 == null || !jugador1.getConvergio() || !jugador2.getConvergio()) {
            boolean noTieneRaices = !jugador1.tieneRaicesEnRegion() || !jugador2.tieneRaicesEnRegion();
            infoNoConvergencia alerta = new infoNoConvergencia(noTieneRaices);
            alerta.setVisible(true);
            return;
        }
           
         //Abrir Carrera
         Carrera carrera = new Carrera(ecuacionText,(int)resSol,(int)resZom, jugador1, jugador2);
         carrera.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtX0SolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX0SolActionPerformed
        // TODO add your handling code here:
        this.setEnabled(true);
    }//GEN-LAST:event_txtX0SolActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        if(ecuacion<7){
        ElegirMenuEcuaciones menu = new ElegirMenuEcuaciones();
        menu.setVisible(true);
        this.dispose();
        }else if(ecuacion ==7){
            ingresarEcLineal lineal = new ingresarEcLineal();
            lineal.setVisible(true);
            this.dispose();
        }else if(ecuacion == 8){
            ingresarEcExponencial exp = new ingresarEcExponencial();
            exp.setVisible(true);
            this.dispose();
        }else if(ecuacion == 9){
            ingresarEcTrigoSen sen = new ingresarEcTrigoSen();
            sen.setVisible(true);
            this.dispose();
        }else if(ecuacion == 10){
            ingresarEcTrigoCos cos = new ingresarEcTrigoCos();
            cos.setVisible(true);
            this.dispose();
        }else if(ecuacion == 11){
            ingresarEcTrigoTan tan = new ingresarEcTrigoTan();
            tan.setVisible(true);
            this.dispose();
        }else if(ecuacion == 12){
            ingresarEcLog log = new ingresarEcLog();
            log.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseEntered
        // TODO add your handling code here:
        btnIniciar.setBackground(new Color(0, 255, 0));//Color Verde
    }//GEN-LAST:event_btnIniciarMouseEntered

    private void btnIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseExited
        // TODO add your handling code here:
         btnIniciar.setBackground(null);
    }//GEN-LAST:event_btnIniciarMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setBackground(new Color(255, 255, 0));//Color amarillo código RGB
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setBackground(null);
    }//GEN-LAST:event_btnSalirMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtX0SolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtX0SolMouseClicked
        // TODO add your handling code here:
        this.setEnabled(true);

    }//GEN-LAST:event_txtX0SolMouseClicked

    private void txtX1SolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX1SolActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtX1SolActionPerformed

    private void txtX1SolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtX1SolMouseClicked
        // TODO add your handling code here:
        this.setEnabled(true);
    }//GEN-LAST:event_txtX1SolMouseClicked

    private void txtX0ZomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtX0ZomMouseClicked
        // TODO add your handling code here:
        this.setEnabled(true);
    }//GEN-LAST:event_txtX0ZomMouseClicked

    private void txtX1ZomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtX1ZomMouseClicked
        // TODO add your handling code here:
        this.setEnabled(true);
    }//GEN-LAST:event_txtX1ZomMouseClicked

    private void cbErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbErrorMouseClicked
        // TODO add your handling code here:
        this.setEnabled(true);
    }//GEN-LAST:event_cbErrorMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbError;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblEcSoldado2;
    private javax.swing.JLabel lblEcuacion;
    private javax.swing.JLabel lblZombie;
    private javax.swing.JTextField txtX0Sol;
    private javax.swing.JTextField txtX0Zom;
    private javax.swing.JTextField txtX1Sol;
    private javax.swing.JTextField txtX1Zom;
    // End of variables declaration//GEN-END:variables
public void labelEc(){
    switch(ecuacion){
            case 1: {lblEcuacion.setText("f(x)= x^(3) - 2x -5");
            ecuacionText="f(x)= x^(3) - 2x -5";
            }
            break;
            case 2:{ lblEcuacion.setText("f(x) = e ^(x) - 3x^(2)");
            ecuacionText="f(x) = e ^(x) - 3x^(2)";
            }
            break;
            case 3: {lblEcuacion.setText("f(x) = sin (x) - x^(2) + 2x +1");
            ecuacionText = "f(x) = sin (x) - x^(2) + 2x +1";
            }
            break;
            case 4: {lblEcuacion.setText("f(x) = log(x) - 2x +3");
            ecuacionText = "f(x) = log(x) - 2x +3";
            }
            break;
            case 5: {lblEcuacion.setText("f(x) = sqr(x) - 2");
            ecuacionText = "f(x) = sqr(x) - 2";
            }
            break;
            case 6: {lblEcuacion.setText("f(x) = x^(2) - 4");
            ecuacionText = "f(x) = x^(2) - 4";
           }
            break;
            case 7: {
            lblEcuacion.setText("f(x) = "+Double.toString(c1)+"* x^5 + "+Double.toString(c2)+"* x^4 +"+Double.toString(c3)+"* x^3 +"+Double.toString(c4)+" * x^2 +"+Double.toString(c5)+"* x +"+Double.toString(c6));
            lblEcuacion.setFont(new Font("OCR A Extended", Font.BOLD, 24));
            ecuacionText = "f(x) = "+Double.toString(c1)+"* x^5 + "+Double.toString(c2)+"* x^4 +"+Double.toString(c3)+"* x^3 +"+Double.toString(c4)+" * x^2 +"+Double.toString(c5)+"* x +"+Double.toString(c6);
                
            }
            break;
            case 8: {
            lblEcuacion.setText("f(x) = "+ Double.toString(c1)+"^("+Double.toString(e1)+"*x0+"+Double.toString(e2)+")+"+Double.toString(c2)+"^("+Double.toString(e3)+"*x1+"+Double.toString(e4)+")+"+Double.toString(c3)+"^("+Double.toString(e5)+"*x1+"+Double.toString(e6)+")");
            lblEcuacion.setFont(new Font("OCR A Extended", Font.BOLD, 24));
            ecuacionText = "f(x) = "+ Double.toString(c1)+"^("+Double.toString(e1)+"*x1+"+Double.toString(e2)+")+"+Double.toString(c2)+"^("+Double.toString(e3)+"*x1+"+Double.toString(e4)+")+"+Double.toString(c3)+"^("+Double.toString(e5)+"*x1+"+Double.toString(e6)+")";
            }
            break;
            case 9: {
            lblEcuacion.setText("f(x) = "+Double.toString(c1)+" * sin("+Double.toString(c2)+"+*x+"+Double.toString(c3)+")+"+Double.toString(c4));
            lblEcuacion.setFont(new Font("OCR A Extended", Font.BOLD, 24));
            ecuacionText = "f(x) = "+Double.toString(c1)+" * sin("+Double.toString(c2)+"+*x+"+Double.toString(c3)+")+"+Double.toString(c4);
            
            }
            break;
            case 10: {
            lblEcuacion.setText("f(x) = "+Double.toString(c1)+" * cos("+Double.toString(c2)+"+*x+"+Double.toString(c3)+")+"+Double.toString(c4));
            lblEcuacion.setFont(new Font("OCR A Extended", Font.BOLD, 24));
            ecuacionText = "f(x) = "+Double.toString(c1)+" * cos("+Double.toString(c2)+"+*x+"+Double.toString(c3)+")+"+Double.toString(c4);
            }
            break;
            case 11: {
            lblEcuacion.setText("f(x) = "+Double.toString(c1)+" * tan("+Double.toString(c2)+"+*x+"+Double.toString(c3)+")+"+Double.toString(c4));
            lblEcuacion.setFont(new Font("OCR A Extended", Font.BOLD, 24));
            ecuacionText = "f(x) = "+Double.toString(c1)+" * tan("+Double.toString(c2)+"+*x+"+Double.toString(c3)+")+"+Double.toString(c4);
            }
            break;
            case 12: {
                
                if (base == "e") {
                    lblEcuacion.setText("f(x) = " +Double.toString(c1)+" * log("+Double.toString(c2)+"*x+"+Double.toString(c3)+")+"+Double.toString(c4));
                    lblEcuacion.setFont(new Font("OCR A Extended", Font.BOLD, 24));
                    ecuacionText = "f(x) = " +Double.toString(c1)+" * log("+Double.toString(c2)+"*x+"+Double.toString(c3)+")+"+Double.toString(c4);

                } else {
                    lblEcuacion.setText("f(x) = " +Double.toString(c1)+" * log10("+Double.toString(c2)+"*x+"+Double.toString(c3)+")+"+Double.toString(c4));
                    lblEcuacion.setFont(new Font("OCR A Extended", Font.BOLD, 24));
                    ecuacionText = "f(x) = " +Double.toString(c1)+" * log10("+Double.toString(c2)+"*x+"+Double.toString(c3)+")+"+Double.toString(c4);
                }
            
            }
            break;
            default: lblEcuacion.setText("No se eligió una ecuación");
            
            
        }
}


}

