/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class ingresarEcMenu extends javax.swing.JFrame {
    
    private String ecuacion;

    /**
     * Creates new form ingresarEcMenu
     */
    public ingresarEcMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Maximizar la pantalla
        this.setExtendedState(MAXIMIZED_BOTH);

        // Clean up open preview windows
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof generarGrafica || window instanceof imagenEcIngreso) {
                window.dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEcExponencial = new javax.swing.JButton();
        btnEcTrigonometrica = new javax.swing.JButton();
        btnEcLogaritmica = new javax.swing.JButton();
        btnEcLineal = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEcExponencial.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEcExponencial.setText("Exponential");
        btnEcExponencial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnEcExponencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEcExponencialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEcExponencialMouseExited(evt);
            }
        });
        btnEcExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcExponencialActionPerformed(evt);
            }
        });

        btnEcTrigonometrica.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEcTrigonometrica.setText("Trigonometric");
        btnEcTrigonometrica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnEcTrigonometrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEcTrigonometricaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEcTrigonometricaMouseExited(evt);
            }
        });
        btnEcTrigonometrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcTrigonometricaActionPerformed(evt);
            }
        });

        btnEcLogaritmica.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEcLogaritmica.setText("Logarithmic");
        btnEcLogaritmica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnEcLogaritmica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEcLogaritmicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEcLogaritmicaMouseExited(evt);
            }
        });
        btnEcLogaritmica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcLogaritmicaActionPerformed(evt);
            }
        });

        btnEcLineal.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnEcLineal.setText("Linear");
        btnEcLineal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        btnEcLineal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEcLinealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEcLinealMouseExited(evt);
            }
        });
        btnEcLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEcLinealActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnRegresar.setText("Return");
        btnRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("Choose the circuit for the race...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEcExponencial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEcTrigonometrica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEcLogaritmica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEcLineal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(359, 359, 359))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnEcLineal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEcExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEcTrigonometrica, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEcLogaritmica, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEcLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcLinealActionPerformed
        // TODO add your handling code here:
        ingresarEcLineal lineal = new ingresarEcLineal();
        lineal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcLinealActionPerformed

    private void btnEcTrigonometricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcTrigonometricaActionPerformed
        // TODO add your handling code here:
        ingresarEcMenuTrigo menu = new ingresarEcMenuTrigo();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcTrigonometricaActionPerformed

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setBackground(new Color(255, 255, 153));//Color amarillo código RGB
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setBackground(null);//Color default
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnEcLinealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcLinealMouseEntered
        // TODO add your handling code here:
         btnEcLineal.setBackground(new Color(255, 153, 0));//Color anaranjado código RGB
    }//GEN-LAST:event_btnEcLinealMouseEntered

    private void btnEcLinealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcLinealMouseExited
        // TODO add your handling code here:
        btnEcLineal.setBackground(null);//Color default
    }//GEN-LAST:event_btnEcLinealMouseExited

    private void btnEcExponencialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcExponencialMouseEntered
        // TODO add your handling code here:
        btnEcExponencial.setBackground(new Color(255, 153, 0));//Color anaranjado código RGB
    }//GEN-LAST:event_btnEcExponencialMouseEntered

    private void btnEcExponencialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcExponencialMouseExited
        // TODO add your handling code here:
        btnEcExponencial.setBackground(null);//Color default
    }//GEN-LAST:event_btnEcExponencialMouseExited

    private void btnEcTrigonometricaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcTrigonometricaMouseEntered
        // TODO add your handling code here:
        btnEcTrigonometrica.setBackground(new Color(255, 153, 0));//Color anaranjado código RGB
    }//GEN-LAST:event_btnEcTrigonometricaMouseEntered

    private void btnEcTrigonometricaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcTrigonometricaMouseExited
        // TODO add your handling code here:
        btnEcTrigonometrica.setBackground(null);//Color default
    }//GEN-LAST:event_btnEcTrigonometricaMouseExited

    private void btnEcLogaritmicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcLogaritmicaMouseEntered
        // TODO add your handling code here:
        btnEcLogaritmica.setBackground(new Color(255, 153, 0));//Color anaranjado código RGB
    }//GEN-LAST:event_btnEcLogaritmicaMouseEntered

    private void btnEcLogaritmicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcLogaritmicaMouseExited
        // TODO add your handling code here:
        btnEcLogaritmica.setBackground(null);//Color default
    }//GEN-LAST:event_btnEcLogaritmicaMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        preEleccion menu = new preEleccion();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEcExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcExponencialActionPerformed
        // TODO add your handling code here:
        ingresarEcExponencial exponencial = new ingresarEcExponencial();
        exponencial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcExponencialActionPerformed

    private void btnEcLogaritmicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcLogaritmicaActionPerformed
        // TODO add your handling code here:
        ingresarEcLog log = new ingresarEcLog();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEcLogaritmicaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEcExponencial;
    private javax.swing.JButton btnEcLineal;
    private javax.swing.JButton btnEcLogaritmica;
    private javax.swing.JButton btnEcTrigonometrica;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
