/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soldadovszombie;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class preEleccion extends javax.swing.JFrame {

    /**
     * Creates new form PreElección
     */
    public preEleccion() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //Maximizar la pantalla
        this.setExtendedState(MAXIMIZED_BOTH);
        
        // Clean up open preview windows
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof generarGrafica || window instanceof imagenEcIngreso) {
                window.dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnElegirEcuacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnIngresarEcuacion = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnIngresarEcuMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btnElegirEcuacion.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnElegirEcuacion.setText("Choose Equation");
        btnElegirEcuacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 255, 255), null, null));
        btnElegirEcuacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnElegirEcuacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnElegirEcuacionMouseExited(evt);
            }
        });
        btnElegirEcuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirEcuacionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setText("How much are you willing to risk?");

        btnIngresarEcuacion.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnIngresarEcuacion.setText("Equation Architect");
        btnIngresarEcuacion.setToolTipText("");
        btnIngresarEcuacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 153), null, null));
        btnIngresarEcuacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarEcuacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarEcuacionMouseExited(evt);
            }
        });
        btnIngresarEcuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEcuacionActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnRegresar.setText("Return");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 0), null, null));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnIngresarEcuMenu.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnIngresarEcuMenu.setText("Equation Constructor");
        btnIngresarEcuMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 204, 255), null, null));
        btnIngresarEcuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarEcuMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarEcuMenuMouseExited(evt);
            }
        });
        btnIngresarEcuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEcuMenuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel2.setText("the equation you choose is your map to the treasure.");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabel3.setText("Select an option and remember");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/Diamond.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gráficos/Diamond.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnIngresarEcuMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnElegirEcuacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIngresarEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElegirEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnIngresarEcuMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnIngresarEcuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElegirEcuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirEcuacionActionPerformed
        // TODO add your handling code here:
        ElegirMenuEcuaciones ecuaciones = new ElegirMenuEcuaciones();
        ecuaciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnElegirEcuacionActionPerformed

    private void btnIngresarEcuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEcuacionActionPerformed
        // TODO add your handling code here:
        calculadora menu = new calculadora();
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnIngresarEcuacionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        infoMetodoSecante info = new infoMetodoSecante();
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIngresarEcuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEcuMenuActionPerformed
        // TODO add your handling code here:
        ingresarEcMenu menu = new ingresarEcMenu();
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnIngresarEcuMenuActionPerformed

    private void btnElegirEcuacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElegirEcuacionMouseEntered
        // TODO add your handling code here:
        btnElegirEcuacion.setBackground(new Color(135, 206, 235));//Celeste claro
    }//GEN-LAST:event_btnElegirEcuacionMouseEntered

    private void btnElegirEcuacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElegirEcuacionMouseExited
        // TODO add your handling code here:
        btnElegirEcuacion.setBackground(null);
    }//GEN-LAST:event_btnElegirEcuacionMouseExited

    private void btnIngresarEcuMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarEcuMenuMouseEntered
        // TODO add your handling code here:
        btnIngresarEcuMenu.setBackground(new Color(135, 206, 250));//azul claro
    }//GEN-LAST:event_btnIngresarEcuMenuMouseEntered

    private void btnIngresarEcuMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarEcuMenuMouseExited
        // TODO add your handling code here:
        btnIngresarEcuMenu.setBackground(null);
    }//GEN-LAST:event_btnIngresarEcuMenuMouseExited

    private void btnIngresarEcuacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarEcuacionMouseEntered
        // TODO add your handling code here:
        btnIngresarEcuacion.setBackground(new Color(70, 130, 180));
    }//GEN-LAST:event_btnIngresarEcuacionMouseEntered

    private void btnIngresarEcuacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarEcuacionMouseExited
        // TODO add your handling code here:
         btnIngresarEcuacion.setBackground(null);
    }//GEN-LAST:event_btnIngresarEcuacionMouseExited

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setBackground(new Color(204, 204, 0));//Color amarillo código RGB
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setBackground(null);
    }//GEN-LAST:event_btnRegresarMouseExited

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegirEcuacion;
    private javax.swing.JButton btnIngresarEcuMenu;
    private javax.swing.JButton btnIngresarEcuacion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
